### ISSUE TITLE
possible HttpClient socket exhaustion

### ISSUE THREAD

**Issue by aliBordbar1992** [mberneti/Kavenegar.Core#3]
in your main class (KavenegarApi.cs) an HttpClient is instantiated in the contructor, which means with every single sms send request through this class, a new HttpClient is created, as you may know, HttpClient is not supposed to be instantiated for each request. 
[here](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-3.1) you can read about HttpClient possible flaws. From documents:

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly.

So, I suggest that you add an overload constructor to the class which takes the HttpClient from the outside. This way it could be injected like a [Typed client](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)

**Comment by mberneti** [comment]
Well done dear @aliBordbar1992  🙌🏼, the #4 pr is merged.
